from PyQt5 import QtCore, QtGui, QtWidgets
from math import *
#chaque bouton qui apparait dans la calculatrice
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 413)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.neufButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("9"))
        self.neufButton.setGeometry(QtCore.QRect(550, 180, 75, 23))
        self.neufButton.setObjectName("neufButton")
        self.diviserButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("/"))
        self.diviserButton.setGeometry(QtCore.QRect(640, 180, 75, 23))
        self.diviserButton.setObjectName("diviserButton")
        self.septButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("7"))
        self.septButton.setGeometry(QtCore.QRect(370, 180, 75, 23))
        self.septButton.setObjectName("septButton")
        self.pointButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.dot_it())
        self.pointButton.setGeometry(QtCore.QRect(460, 300, 75, 23))
        self.pointButton.setObjectName("pointButton")
        self.piButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("pi"))
        self.piButton.setGeometry(QtCore.QRect(190, 300, 75, 23))
        self.piButton.setObjectName("piButton")
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("delete"))
        self.deleteButton.setGeometry(QtCore.QRect(640, 140, 75, 23))
        self.deleteButton.setObjectName("deleteButton")
        self.cosButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("cos"))
        self.cosButton.setGeometry(QtCore.QRect(190, 220, 75, 23))
        self.cosButton.setObjectName("cosButton")
        self.unButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("1"))
        self.unButton.setGeometry(QtCore.QRect(370, 260, 75, 23))
        self.unButton.setObjectName("unButton")
        self.resultatButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.math_it())
        self.resultatButton.setGeometry(QtCore.QRect(640, 300, 75, 23))
        self.resultatButton.setObjectName("resultatButton")
        self.plusButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("+"))
        self.plusButton.setGeometry(QtCore.QRect(550, 300, 75, 23))
        self.plusButton.setObjectName("plusButton")
        self.quatreButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("4"))
        self.quatreButton.setGeometry(QtCore.QRect(370, 220, 75, 23))
        self.quatreButton.setObjectName("quatreButton")
        self.parentheseGaucheButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("("))
        self.parentheseGaucheButton.setGeometry(QtCore.QRect(190, 140, 75, 23))
        self.parentheseGaucheButton.setObjectName("parentheseGaucheButton")
        self.huitButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("8"))
        self.huitButton.setGeometry(QtCore.QRect(460, 180, 75, 23))
        self.huitButton.setObjectName("huitButton")
        self.troisButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("3"))
        self.troisButton.setGeometry(QtCore.QRect(550, 260, 75, 23))
        self.troisButton.setObjectName("troisButton")
        self.zeroButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("0"))
        self.zeroButton.setGeometry(QtCore.QRect(370, 300, 75, 23))
        self.zeroButton.setObjectName("zeroButton")
        self.outputLabel = QtWidgets.QLabel(self.centralwidget)
        self.outputLabel.setGeometry(QtCore.QRect(100, 30, 611, 91))
        font = QtGui.QFont()
        font.setPointSize(42)
        self.outputLabel.setFont(font)
        self.outputLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outputLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.outputLabel.setObjectName("outputLabel")
        self.carreButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("**2"))
        self.carreButton.setGeometry(QtCore.QRect(280, 260, 75, 23))
        self.carreButton.setObjectName("carreButton")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("**"))
        self.pushButton_11.setGeometry(QtCore.QRect(280, 300, 75, 23))
        self.pushButton_11.setObjectName("pushButton_11")
        self.multiplierButton_2 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("*"))
        self.multiplierButton_2.setGeometry(QtCore.QRect(640, 220, 75, 23))
        self.multiplierButton_2.setObjectName("multiplierButton_2")
        self.sinButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("sin"))
        self.sinButton.setGeometry(QtCore.QRect(190, 180, 75, 23))
        self.sinButton.setObjectName("sinButton")
        self.sixButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("6"))
        self.sixButton.setGeometry(QtCore.QRect(550, 220, 75, 23))
        self.sixButton.setObjectName("sixButton")
        self.moinsButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("-"))
        self.moinsButton.setEnabled(True)
        self.moinsButton.setGeometry(QtCore.QRect(640, 260, 75, 23))
        self.moinsButton.setObjectName("moinsButton")
        self.parentheseDroiteButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it(")"))
        self.parentheseDroiteButton.setGeometry(QtCore.QRect(280, 140, 75, 23))
        self.parentheseDroiteButton.setObjectName("parentheseDroiteButton")
        self.poucentageButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("%"))
        self.poucentageButton.setGeometry(QtCore.QRect(280, 180, 75, 23))
        self.poucentageButton.setObjectName("poucentageButton")
        self.tanButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("tan"))
        self.tanButton.setGeometry(QtCore.QRect(190, 260, 75, 23))
        self.tanButton.setObjectName("tanButton")
        self.cinqButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("5"))
        self.cinqButton.setGeometry(QtCore.QRect(460, 220, 75, 23))
        self.cinqButton.setObjectName("cinqButton")
        self.racinecarreButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("sqrt"))
        self.racinecarreButton.setGeometry(QtCore.QRect(280, 220, 75, 23))
        self.racinecarreButton.setObjectName("racinecarreButton")
        self.deuxButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("2"))
        self.deuxButton.setGeometry(QtCore.QRect(460, 260, 75, 23))
        self.deuxButton.setObjectName("deuxButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

#faire les calculs
    def math_it(self):
        screen = self.outputLabel.text()
        try:
            answer = eval(screen)
            self.outputLabel.setText(str(answer))
        except:
            self.outputLabel.setText("Erreur Syntaxe")

#pas repeter les virgules
        
    def dot_it(self):
        screen = self.outputLabel.text()
        if screen[-1] == ".":
            pass
        else:
            self.outputLabel.setText(f'{screen}.')

#supprimer
    def press_it(self, pressed):
        if pressed == "delete":
            self.outputLabel.setText("0")
        else:
            if self.outputLabel.text() == "0":
                self.outputLabel.setText("")
            self.outputLabel.setText(f'{self.outputLabel.text()}{pressed}')
            
#afficher tous les bouton
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.neufButton.setText(_translate("MainWindow", "9"))
        self.diviserButton.setText(_translate("MainWindow", "÷"))
        self.septButton.setText(_translate("MainWindow", "7"))
        self.pointButton.setText(_translate("MainWindow", "."))
        self.piButton.setText(_translate("MainWindow", "π"))
        self.deleteButton.setText(_translate("MainWindow", "Delete"))
        self.cosButton.setText(_translate("MainWindow", "cos"))
        self.unButton.setText(_translate("MainWindow", "1"))
        self.resultatButton.setText(_translate("MainWindow", "="))
        self.plusButton.setText(_translate("MainWindow", "+"))
        self.quatreButton.setText(_translate("MainWindow", "4"))
        self.parentheseGaucheButton.setText(_translate("MainWindow", "("))
        self.huitButton.setText(_translate("MainWindow", "8"))
        self.troisButton.setText(_translate("MainWindow", "3"))
        self.zeroButton.setText(_translate("MainWindow", "0"))
        self.outputLabel.setText(_translate("MainWindow", "0"))
        self.carreButton.setText(_translate("MainWindow", "^"))
        self.pushButton_11.setText(_translate("MainWindow", "e"))
        self.multiplierButton_2.setText(_translate("MainWindow", "x"))
        self.sinButton.setText(_translate("MainWindow", "sin"))
        self.sixButton.setText(_translate("MainWindow", "6"))
        self.moinsButton.setText(_translate("MainWindow", "-"))
        self.parentheseDroiteButton.setText(_translate("MainWindow", ")"))
        self.poucentageButton.setText(_translate("MainWindow", "%"))
        self.tanButton.setText(_translate("MainWindow", "tan"))
        self.cinqButton.setText(_translate("MainWindow", "5"))
        self.racinecarreButton.setText(_translate("MainWindow", "√ "))
        self.deuxButton.setText(_translate("MainWindow", "2"))

#creation de l'application
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
